version: '3.4'

services:
  find_square:
    image: duckfish/find_square:0.1.0
    build:
      context: .
      dockerfile: dockerfile
    container_name: find_square
    env_file:
      - find_square.env
    ports:
      - '8000:8000'
    volumes:
      - /c/Projects/logs:/find_square/logs
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb
    env_file:
      - db.env
    ports:
      - '27017:27017'
    volumes:
      - /c/Projects/mongodb:/data/db