version: 1
formatters:
  simple:
    format: '%(asctime)s [%(name)s] [%(levelname)s]  %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file_uvicorn:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/uvicorn.log
    maxBytes: 10000000
    backupCount: 1
  file_find_square:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/find_square.log
    maxBytes: 10000000
    backupCount: 1
loggers:
  find_square:
    level: DEBUG
    handlers: [console, file_find_square]
    propagate: no
  uvicorn.error:
    level: INFO
    handlers: [console, file_uvicorn]
    propagate: no
  uvicorn.access:
    level: INFO
    handlers: [console, file_uvicorn]
    propagate: no
root:
  level: DEBUG
  handlers: [console]