version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file_uvicorn:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/uvicorn.log
    maxBytes: 10000000
    backupCount: 1
  file_pet:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/pet.log
    maxBytes: 10000000
    backupCount: 1
loggers:
  pet:
    level: INFO
    handlers: [console, file_pet]
    propagate: no
  uvicorn.error:
    level: INFO
    handlers: [console, file_uvicorn]
    propagate: no
  uvicorn.access:
    level: INFO
    handlers: [console, file_uvicorn]
    propagate: no
root:
  level: DEBUG
  handlers: [console]